	SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,RPL, &	  
        DDSDDT,DRPLDE,DRPLDT,STRAN,DSTRAN,TIME,DTIME,TEMP, &
	  DTEMP,PREDEF,DPRED,CMNAME,NDI,NSHR,NTENS,NSTATV,PROPS,& 
	  NPROPS,COORDS,DROT,PNEWDT,CELENT,DFGRD0,DFGRD1,NOEL,NPT,& 
	  LAYER,KSPT,JSTEP,KINC)
      INCLUDE 'ABA_PARAM.INC'
      implicit none
      
      CHARACTER*80 CMNAME
      INTEGER, INTENT(IN):: NTENS,NSTATV,NPROPS
      real, intent(inout) :: STRESS(NTENS),STATEV(NSTATV), DDSDDE(NTENS,NTENS), &
           DDSDDT(NTENS),DRPLDE(NTENS),STRAN(NTENS),DSTRAN(NTENS), & 
           TIME(2),PREDEF(1),DPRED(1),PROPS(NPROPS),COORDS(3), &
           DROT(3,3),DFGRD0(3,3),DFGRD1(3,3),JSTEP(4)
      real, intent(in) :: SSE,SPD,SCD,RPL,DRPLDT,DTEMP,TEMP,DTIME,NDI,NSHR, &
      PNEWDT,CELENT,NOEL,NPT, LAYER,KSPT,KINC

	real, parameter :: ONE=1.0 , TWO=2.0
      real :: I,J,E,ANU,ALAMBDA,AMU
		E= props(1)
		ANU= props(2)
		ALAMBDA= E*ANU/(ONE+ANU)/(ONE - TWO*ANU)
		AMU=E/(ONE+ANU)/2
		DO I=1,NTENS
			DO J=1,NTENS
			DDSDDE(I,J)=0.0
			END DO
		END DO
		DDSDDE(1,1)=(ALAMBDA+TWO*AMU)
		DDSDDE(2,2)=(ALAMBDA+TWO*AMU)
		DDSDDE(3,3)=(ALAMBDA+TWO*AMU)
		DDSDDE(4,4)= AMU
		DDSDDE(5,5)= AMU
		DDSDDE(6,6)= AMU
		DDSDDE(1,2)= ALAMBDA
		DDSDDE(1,3)= ALAMBDA
		DDSDDE(2,3)= ALAMBDA
		DDSDDE(3,1)= ALAMBDA
		DDSDDE(3,1)= ALAMBDA
		DDSDDE(3,2)= ALAMBDA
			DO I=1,NTENS
				DO J=1,NTENS
				STRESS(I)= STRESS(I)+DDSDDE(I,J)*DSTRAN(J)
				END DO
			END DO
	
      RETURN
      END SUBROUTINE UMAT